version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  redis:
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379
      - 6380:6380
  api_rails_mongo:
    build: ./
    command: rails s -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - 8888:8888
    depends_on:
      - mongo
      - redis
#
# networks:
#   api_cache:
#     ipam:
#       drive: default
#         config:
#                 - subnet: 172.16.238.0/24
